use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'LittleDefend_Example' do
  pod 'LittleDefend', :path => '../'

  target 'LittleDefend_Tests' do
    inherit! :search_paths

    
  end
end
